package shiro_test

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
	
	def publicActions = [
		signup: ['index', 'register'],
<<<<<<< HEAD
		home: ['*'],
=======
>>>>>>> 5596933d044abc50e7d7ca724273c94e949f6669
		auth:['*']	
	]
	
	private boolean findAction(controllerName, actionName){
		def c = publicActions[controllerName]
		return(c)?c.find{(it==actionName || it=='*')}!=null:false
	}
	
	def filters = {
		all(uri: "/**"){
			before = {
				def isPublic = findAction(controllerName,actionName)
				
				if(isPublic){
					return true
				}
				
<<<<<<< HEAD
				if (!controllerName || controllerName == 'assets'){
=======
				if (!controllerName){
>>>>>>> 5596933d044abc50e7d7ca724273c94e949f6669
					return true
				}
				
				accessControl()
			}
		}
	}
}
